name: autoencoder
tag: ""
seed: 42


dataset:
  name: standard_data
  scene: none
  root_dir: MNIST
  train_split: "train"
  val_split: "val"
  test_split: "test"
  num_workers: 8
  batch_size: 32

model:
  name: simple_net
  in_channel: 3 
  out_channel: 10
  hid: 128
  layer_num: 5
  optimizer:
    name: AdamW
    args:
      lr: 1e-3
      betas: [0.9, 0.99]
      eps: 1.e-15
      weight_decay: 1e-5
  scheduler:
    name: step
    lr_decay_rate: 0.5
    lr_decay_steps: 20
    lr_decay_min_lr: 1e-5
  loss: mse

checkpoint:
  save_top_k: 5
  every_n_train_steps: 2000
  monitor: 'val_loss'
  save_last: true

trainer:
  max_steps: 40000
  log_every_n_steps: 50
  num_sanity_val_steps: 0
  val_check_interval: 1000
  limit_train_batches: 1.0
  limit_val_batches: 4
  enable_progress_bar: true
  precision: 16
  accumulate_grad_batches: 1
  accelerator: 'mps'
  