wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.9.16
    cli_version: 0.16.1
    framework: lightning
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1704640255.735648
    t:
      1:
      - 1
      - 5
      - 9
      - 41
      - 53
      - 55
      - 103
      3:
      - 13
      - 23
      4: 3.9.16
      5: 0.16.1
      8:
      - 5
      13: darwin-arm64
