wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.9.16
    cli_version: 0.16.1
    framework: lightning
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1704640255.735648
    t:
      1:
      - 1
      - 5
      - 9
      - 41
      - 53
      - 55
      - 103
      2:
      - 1
      - 5
      - 9
      - 41
      - 53
      - 55
      - 103
      3:
      - 7
      - 13
      - 23
      4: 3.9.16
      5: 0.16.1
      8:
      - 4
      - 5
      13: darwin-arm64
    m:
    - 1: trainer/global_step
      6:
      - 3
    - 1: lr-AdamW
      5: 1
      6:
      - 1
    - 1: loss_step
      5: 1
      6:
      - 1
    - 1: epoch
      5: 1
      6:
      - 1
name:
  desc: null
  value: simple_net
in_channel:
  desc: null
  value: 3
out_channel:
  desc: null
  value: 10
hid:
  desc: null
  value: 128
layer_num:
  desc: null
  value: 5
optimizer:
  desc: null
  value: '{''name'': ''AdamW'', ''args'': {''lr'': 0.001, ''betas'': [0.9, 0.99],
    ''eps'': 1e-15, ''weight_decay'': 1e-05}}'
scheduler:
  desc: null
  value: '{''name'': ''step'', ''lr_decay_rate'': 0.5, ''lr_decay_steps'': 20, ''lr_decay_min_lr'':
    1e-05}'
loss:
  desc: null
  value: mse
save_dir:
  desc: null
  value: ./exp/autoencoder/@20240107-231053/save
